import type { Metadata } from 'next';
import './globals.css';
import AuthProvider from '@/common/components/provider/AuthProvider';
import { ThemeProvider } from '@/common/components/provider/ThemeProvider';
import { cn } from '@/common/lib/utils';
import { fontPoppins } from '@/common/lib/fonts';
import { Toaster } from 'sonner';
import { AOSInit } from '@/common/components/provider/AOSInit';
import 'aos/dist/aos.css';
import { AuthListener } from '@/common/components/provider/AuthListener';
import ReactQueryProvider from '@chirp/api/src/providers/ReactQueryProvider';
import ApiClientProvider from '@/common/components/provider/ApiClientProvider';

export const metadata: Metadata = {
    title: {
        default: 'Chirp',
        template: '%s | Chirp',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            lang="en"
            className={cn(fontPoppins.className, 'antialiased')}
            suppressHydrationWarning
        >
            <body>
                <AOSInit />
                <AuthProvider>
                    <ApiClientProvider>
                        <ReactQueryProvider>
                            <AuthListener />
                            <ThemeProvider
                                attribute="class"
                                defaultTheme="dark"
                                enableSystem
                                disableTransitionOnChange
                            >
                                <Toaster richColors position="bottom-center" />
                                {children}
                            </ThemeProvider>
                        </ReactQueryProvider>
                    </ApiClientProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
